default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: healthchecker_dev

test:
  <<: *default
  database: healthchecker_sandbox

production:
  <<: *default
  database: healthchecker_production # 任意のデータベース名
  username: kmasa1569 # 任意のユーザー名
  password: request.env['DB_PASSWORD'] # 任意のパスワー
  adapter: postgresql
  encoding: unicode
  pool:  <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>